newFirstName="xpath://input[@placeholder='Name']"
newLastName="xpath://input[@data-qa='signup-email']"
btnSubmit="xpath://button[normalize-space()='Signup']"
enterPass="id:password"
enterFirstName="id:first_name"
enterLastName="id:last_name"
enterAddress="address1"
selectCountry="country"
enterState="id:state"
enterCity="id:city"
enterZipcode="id:zipcode"
enterPhone="id:mobile_number"
btnCreate="xpath://button[normalize-space()='Create Account']"